# We use IBM Java 8 so that we can use the Health Center sampling profiler
FROM icr.io/appcafe/open-liberty:kernel-slim-java8-ibmjava-ubi

# podman supports *.in Containerfiles which can #include snippets from other files
# which we use to share Containerfile snippets between the vanilla and InstantOn Containerfiles
# https://docs.podman.io/en/latest/markdown/podman-build.1.html

#include "Containerfile.shared1"

# Add some more advanced features that InstantOn can't handle yet
COPY --chown=default:root src/main/liberty/config/configDropins/defaults/advanced.xml /config/configDropins/defaults/advanced.xml

# This script will grow the image to be fit-for-purpose using featureUtility based on the configured features.
# Only available in 'kernel-slim'. The 'full' tag already includes all features for convenience.
RUN features.sh

#include "Containerfile.shared2"
